Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/election.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &ECZ
    Name: ECZMSP
    ID: ECZMSP
    MSPDir: crypto-config/peerOrganizations/ecz.election.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ECZMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ECZMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ECZMSP.admin')"
    AnchorPeers:
      - Host: peer0.ecz.election.com
        Port: 7051

  - &Voter
    Name: VoterMSP
    ID: VoterMSP
    MSPDir: crypto-config/peerOrganizations/voter.election.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('VoterMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('VoterMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('VoterMSP.admin')"
    AnchorPeers:
      - Host: peer0.voter.election.com
        Port: 8051

Application: &ApplicationDefaults
  Organizations:

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.election.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

Profiles:
  TwoOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *ECZ
        - *Voter

  TwoOrgsChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *ECZ
        - *Voter 